# Site
name: "Byte of Code"
description: "8 Bits of Technical Madness"
meta_description: "!Available"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-122845144-1'
disqus: 'hashd-blog'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  Kiran:
    name: Kiran Danduprolu
    display_name: Kiran
    gravatar: 7ce29cba83b9fb3700ee19c1a0511a34
    email: kirandanduprolu@gmail.com
    web: https://kiran.danduprolu.com
    twitter: https://twitter.com/_hash_d
    description: "Author of uvCharts, Marvelous and Claft"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
