# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               '#Blog'
tagline:             'Insanity restored'
description:         'Blog by <a href="http://www.github.com/hashd" target="_blank">hashd</a>'
url:                 http://www.github.com/hashd
baseurl:             'http://kiran.danduprolu.com'
paginate:            5

# About/contact
author:
  name:              Kiran Danduprolu
  url:               https://www.github.com/hashd
  email:             k@danduprolu.com

# Custom vars
version:             0.1.0

assets:
  sources:
    - _assets/fonts
